/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteImport } from './routes/app'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CoventryRouteImport } from './routes/coventry'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GoRouteImport } from './routes/go'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LondonRouteImport } from './routes/london'
import { Route as OnlineCoachingRouteImport } from './routes/online-coaching'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProgrammesRouteImport } from './routes/programmes'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppCoachRouteImport } from './routes/app/coach'
import { Route as AppNutritionRouteImport } from './routes/app/nutrition'
import { Route as AppPlanRouteImport } from './routes/app/plan'
import { Route as AppProgressRouteImport } from './routes/app/progress'
import { Route as ProgramsSlugRouteImport } from './routes/programs.$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CoventryRoute = CoventryRouteImport.update({
  id: '/coventry',
  path: '/coventry',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GoRoute = GoRouteImport.update({
  id: '/go',
  path: '/go',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LondonRoute = LondonRouteImport.update({
  id: '/london',
  path: '/london',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlineCoachingRoute = OnlineCoachingRouteImport.update({
  id: '/online-coaching',
  path: '/online-coaching',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesRoute = ProgrammesRouteImport.update({
  id: '/programmes',
  path: '/programmes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCoachRoute = AppCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AppRoute,
} as any)
const AppNutritionRoute = AppNutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanRoute = AppPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AppRoute,
} as any)
const AppProgressRoute = AppProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AppRoute,
} as any)
const ProgramsSlugRoute = ProgramsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProgramsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/coventry': typeof CoventryRoute
  '/faq': typeof FaqRoute
  '/go': typeof GoRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/london': typeof LondonRoute
  '/online-coaching': typeof OnlineCoachingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/programmes': typeof ProgrammesRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/quiz': typeof QuizRoute
  '/reviews': typeof ReviewsRoute
  '/app/coach': typeof AppCoachRoute
  '/app/nutrition': typeof AppNutritionRoute
  '/app/plan': typeof AppPlanRoute
  '/app/progress': typeof AppProgressRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/coventry': typeof CoventryRoute
  '/faq': typeof FaqRoute
  '/go': typeof GoRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/london': typeof LondonRoute
  '/online-coaching': typeof OnlineCoachingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/programmes': typeof ProgrammesRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/quiz': typeof QuizRoute
  '/reviews': typeof ReviewsRoute
  '/app/coach': typeof AppCoachRoute
  '/app/nutrition': typeof AppNutritionRoute
  '/app/plan': typeof AppPlanRoute
  '/app/progress': typeof AppProgressRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/coventry': typeof CoventryRoute
  '/faq': typeof FaqRoute
  '/go': typeof GoRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/london': typeof LondonRoute
  '/online-coaching': typeof OnlineCoachingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/programmes': typeof ProgrammesRoute
  '/programs': typeof ProgramsRouteWithChildren
  '/quiz': typeof QuizRoute
  '/reviews': typeof ReviewsRoute
  '/app/coach': typeof AppCoachRoute
  '/app/nutrition': typeof AppNutritionRoute
  '/app/plan': typeof AppPlanRoute
  '/app/progress': typeof AppProgressRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/app'
    | '/contact'
    | '/coventry'
    | '/faq'
    | '/go'
    | '/inbox'
    | '/login'
    | '/london'
    | '/online-coaching'
    | '/pricing'
    | '/privacy'
    | '/programmes'
    | '/programs'
    | '/quiz'
    | '/reviews'
    | '/app/coach'
    | '/app/nutrition'
    | '/app/plan'
    | '/app/progress'
    | '/programs/$slug'
    | '/app/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/coventry'
    | '/faq'
    | '/go'
    | '/inbox'
    | '/login'
    | '/london'
    | '/online-coaching'
    | '/pricing'
    | '/privacy'
    | '/programmes'
    | '/programs'
    | '/quiz'
    | '/reviews'
    | '/app/coach'
    | '/app/nutrition'
    | '/app/plan'
    | '/app/progress'
    | '/programs/$slug'
    | '/app'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/app'
    | '/contact'
    | '/coventry'
    | '/faq'
    | '/go'
    | '/inbox'
    | '/login'
    | '/london'
    | '/online-coaching'
    | '/pricing'
    | '/privacy'
    | '/programmes'
    | '/programs'
    | '/quiz'
    | '/reviews'
    | '/app/coach'
    | '/app/nutrition'
    | '/app/plan'
    | '/app/progress'
    | '/programs/$slug'
    | '/app/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRouteWithChildren
  ContactRoute: typeof ContactRoute
  CoventryRoute: typeof CoventryRoute
  FaqRoute: typeof FaqRoute
  GoRoute: typeof GoRoute
  InboxRoute: typeof InboxRoute
  LoginRoute: typeof LoginRoute
  LondonRoute: typeof LondonRoute
  OnlineCoachingRoute: typeof OnlineCoachingRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProgrammesRoute: typeof ProgrammesRoute
  ProgramsRoute: typeof ProgramsRouteWithChildren
  QuizRoute: typeof QuizRoute
  ReviewsRoute: typeof ReviewsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coventry': {
      id: '/coventry'
      path: '/coventry'
      fullPath: '/coventry'
      preLoaderRoute: typeof CoventryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go': {
      id: '/go'
      path: '/go'
      fullPath: '/go'
      preLoaderRoute: typeof GoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/london': {
      id: '/london'
      path: '/london'
      fullPath: '/london'
      preLoaderRoute: typeof LondonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online-coaching': {
      id: '/online-coaching'
      path: '/online-coaching'
      fullPath: '/online-coaching'
      preLoaderRoute: typeof OnlineCoachingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes': {
      id: '/programmes'
      path: '/programmes'
      fullPath: '/programmes'
      preLoaderRoute: typeof ProgrammesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/coach': {
      id: '/app/coach'
      path: '/coach'
      fullPath: '/app/coach'
      preLoaderRoute: typeof AppCoachRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/nutrition': {
      id: '/app/nutrition'
      path: '/nutrition'
      fullPath: '/app/nutrition'
      preLoaderRoute: typeof AppNutritionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/plan': {
      id: '/app/plan'
      path: '/plan'
      fullPath: '/app/plan'
      preLoaderRoute: typeof AppPlanRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/progress': {
      id: '/app/progress'
      path: '/progress'
      fullPath: '/app/progress'
      preLoaderRoute: typeof AppProgressRouteImport
      parentRoute: typeof AppRoute
    }
    '/programs/$slug': {
      id: '/programs/$slug'
      path: '/$slug'
      fullPath: '/programs/$slug'
      preLoaderRoute: typeof ProgramsSlugRouteImport
      parentRoute: typeof ProgramsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppCoachRoute: typeof AppCoachRoute
  AppNutritionRoute: typeof AppNutritionRoute
  AppPlanRoute: typeof AppPlanRoute
  AppProgressRoute: typeof AppProgressRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCoachRoute: AppCoachRoute,
  AppNutritionRoute: AppNutritionRoute,
  AppPlanRoute: AppPlanRoute,
  AppProgressRoute: AppProgressRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ProgramsRouteChildren {
  ProgramsSlugRoute: typeof ProgramsSlugRoute
}

const ProgramsRouteChildren: ProgramsRouteChildren = {
  ProgramsSlugRoute: ProgramsSlugRoute,
}

const ProgramsRouteWithChildren = ProgramsRoute._addFileChildren(
  ProgramsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppRoute: AppRouteWithChildren,
  ContactRoute: ContactRoute,
  CoventryRoute: CoventryRoute,
  FaqRoute: FaqRoute,
  GoRoute: GoRoute,
  InboxRoute: InboxRoute,
  LoginRoute: LoginRoute,
  LondonRoute: LondonRoute,
  OnlineCoachingRoute: OnlineCoachingRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProgrammesRoute: ProgrammesRoute,
  ProgramsRoute: ProgramsRouteWithChildren,
  QuizRoute: QuizRoute,
  ReviewsRoute: ReviewsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
